# Generated by Django 3.2.8 on 2022-12-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
