# Generated by Django 3.2.8 on 2023-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20230226_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='内容'),
        ),
    ]
